#cloud-config
hostname: ubuntu-2404-template-test
manage_etc_hosts: true
users:
  - default
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - systemctl start qemu-guest-agent
  - systemctl is-active qemu-guest-agent
